[package]
edition = "2021"
name = "craft-burn"
version = "0.1.0"

[dependencies]
float-ord = "*"
half = "*"
image = "*"
imageproc = "*"
rayon = "*"

[dependencies.burn]
features = ["wgpu", "cuda-jit", "wgpu-spirv", "tch"]
#git = "https://github.com/tracel-ai/burn.git"
path = "../burn/crates/burn"
